### ISSUE TITLE
[BUG]服务器重启后重载插件发生空指针错误

### ISSUE THREAD

**Issue by ZoruaFox** [DoomsdaySociety/RaidLimiter#1]
[07:19:30 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
[07:19:30 WARN]:        at RaidLimiter-1.1-beta.jar//fun.doomteam.raidlimiter.RaidData.reloadConfig(RaidData.java:99)
[07:19:30 WARN]:        at RaidLimiter-1.1-beta.jar//fun.doomteam.raidlimiter.RaidLimiter.reloadConfig(RaidLimiter.java:65)
[07:19:30 WARN]:        at RaidLimiter-1.1-beta.jar//fun.doomteam.raidlimiter.RaidLimiter.onEnable(RaidLimiter.java:44)
[07:19:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:19:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:19:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[07:19:30 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[07:19:30 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[07:19:30 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[07:19:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[07:19:30 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[07:19:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[07:19:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

此问题在删除data.yml后消失，但必须在删除此文件后手动重载

**Comment by MrXiaoM** [comment]
很抱歉因为学业原因我没有看到你的issue，目前问题已修复，详见我刚提交的 commit 和 release
